export const quotes = [
  "Christmas is not a time nor a season, but a state of mind.",
  "The best way to spread Christmas cheer is singing loud for all to hear.",
  "Christmas waves a magic wand over this world, and behold, everything is softer and more beautiful.",
  "Christmas isn't a season. It's a feeling.",
  "Peace on earth will come to stay, when we live Christmas every day.",
  "Christmas is doing a little something extra for someone.",
  "The joy of brightening other lives becomes for us the magic of the holidays.",
  "Christmas is the day that holds all time together.",
  "Christmas is a season not only of rejoicing but of reflection.",
  "May your days be merry and bright, and may all your Christmases be white.",
  "Gifts of time and love are surely the basic ingredients of a truly merry Christmas.",
  "One of the most glorious messes in the world is the mess created in the living room on Christmas day.",
  "Christmas is the spirit of giving without a thought of getting.",
  "He who has not Christmas in his heart will never find it under a tree.",
  "Christmas is a necessity. There has to be at least one day of the year to remind us that we're here for something else besides ourselves.",
  "I will honor Christmas in my heart, and try to keep it all the year.",
  "At Christmas, all roads lead home.",
  "Christmas is the season for kindling the fire of hospitality in the hall, the genial flame of charity in the heart.",
  "The best of all gifts around any Christmas tree: the presence of a happy family all wrapped up in each other.",
  "Christmas, my child, is love in action.",
  "Blessed is the season which engages the whole world in a conspiracy of love.",
  "Christmas is a bridge. We need bridges as the river of time flows past.",
  "From home to home, and heart to heart, from one place to another. The warmth and joy of Christmas brings us closer to each other.",
  "Christmas is the tonic for our souls.",
  "The smells of Christmas are the smells of childhood.",
  "Christmas is a time when you get homesick — even when you're home.",
  "Christmas is forever, not for just one day.",
  "Christmas is a piece of one's home that one carries in one's heart.",
  "Christmas is love, wrapped in hope and tied with joy.",
  "The spirit of Christmas is the spirit of love and of generosity and of goodness.",
  "Christmas is not about opening gifts, but about opening your heart.",
  "Christmas is the season of joy, of holiday greetings exchanged, of gift-giving, and of families united.",
  "Christmas is a season of gladness, a season of cheer, a season of good times, a season of love.",
  "Christmas is a season for kindling the fire of hospitality in the hall, the genial flame of charity in the heart.",
  "Christmas is the day that holds all time together.",
  "Christmas is the magic that we carry in our hearts.",
  "Christmas is a stocking stuffed with sugary goodness.",
  "Christmas is the golden key that unlocks the door to our hearts.",
  "The Christmas spirit is a spirit of giving and forgiving.",
  "Christmas is the season that unites families, friends, and communities.",
  "Christmas is a blanket of peace that covers the earth.",
  "Christmas is a celebration of love, joy, and hope.",
  "Christmas is a season of wonder and delight.",
  "Christmas is a feeling of warmth, kindness, and generosity.",
  "Christmas is a time to cherish memories, create new ones, and embrace the joy of giving.",
  "Christmas is a song that warms the heart and lifts the spirit.",
  "Christmas is a time for sharing happiness and spreading love.",
  "Christmas is a canvas, and love is the paint.",
  "Christmas is a festival of light, shining in the hearts of all.",
  "Christmas is a time when hearts are open and spirits are high.",
  "Christmas is the art of making memories special.",
  "Christmas is a season of faith, hope, and joy.",
  "Christmas is a time to pause, reflect, and give thanks.",
  "Christmas is a celebration of togetherness and goodwill.",
  "Christmas is a spark that ignites the flame of love in every heart.",
  "Christmas is the whisper of love in the quiet moments.",
  "Christmas is the laughter of children, the warmth of family, and the glow of lights.",
  "Christmas is a moment to believe in miracles and magic.",
  "Christmas is a treasure chest of memories, laughter, and love.",
  "Christmas is the melody of joy that fills the air.",
  "Christmas is a reminder of the goodness in the world.",
  "Christmas is a gift of love that keeps giving.",
  "Christmas is a time to forgive, forget, and embrace.",
  "Christmas is a journey of the heart, leading to love and joy.",
  "Christmas is a season to inspire hope and kindness.",
  "Christmas is the magic that makes ordinary days extraordinary.",
  "Christmas is the joy of giving, the delight of receiving, and the warmth of being together.",
  "Christmas is the sparkle in the eyes of those we love.",
  "Christmas is a light that guides us through the darkest days.",
  "Christmas is a season to celebrate life, love, and friendship.",
  "Christmas is the miracle that happens when hearts open wide.",
  "Christmas is a time for laughter, joy, and making memories.",
  "Christmas is the time when love grows stronger and hearts are lighter.",
  "Christmas is a celebration of hope and happiness.",
  "Christmas is the season when magic lives in our hearts.",
  "Christmas is a reminder that love is the greatest gift of all.",
  "Christmas is a season for giving, sharing, and caring.",
  "Christmas is a tapestry of traditions, love, and joy.",
  "Christmas is a time to gather, to rejoice, and to remember.",
  "Christmas is the light that shines in the darkness.",
  "Christmas is a time to celebrate the goodness of humanity.",
  "Christmas is the heartbeat of the holiday season.",
  "Christmas is a festival of love, laughter, and light.",
  "Christmas is a time when dreams and hope come alive.",
  "Christmas is a season of miracles, big and small.",
  "Christmas is a celebration of kindness, generosity, and joy.",
  "Christmas is a time to open our hearts to others.",
  "Christmas is a symphony of love, joy, and giving.",
  "Christmas is the joy of seeing the world through the eyes of children.",
  "Christmas is the magic of kindness in motion.",
  "Christmas is the spirit that makes life brighter and hearts lighter.",
  "Christmas is the season of giving from the heart, not from the wallet.",
  "Christmas is a celebration of all that is good and true.",
  "Christmas is the warmth that melts the coldest heart.",
  "Christmas is a journey to the heart of love and joy.",
  "Christmas is a time to spread love and happiness to everyone.",
  "Christmas is a festival of peace, love, and joy.",
  "Christmas is the joy that lingers long after the lights are gone.",
  "Christmas is a story written in the language of love.",
  "Christmas is a time when the world feels like home.",
  "Christmas is a light in the darkest nights.",
  "Christmas is the promise of hope, the gift of love, and the spirit of joy.",
  "Christmas is the celebration of life, love, and giving.",
  "Christmas is a time for kindness, compassion, and joy.",
  "Christmas is a season of generosity and gratitude.",
  "Christmas is a memory, a feeling, and a gift that never fades."
];
